/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include <evernote/NoteStore_constants.h>

namespace evernote { namespace edam {

const NoteStoreConstants g_NoteStore_constants;

NoteStoreConstants::NoteStoreConstants() {
}

}} // namespace

